[package]
name = "udp-client"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]
edition = "2018"

[dependencies]
nix = "0.10.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"
toml = "0.4"
