[package]
name = "nsl-duplex-d2"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
radio-api = { path = "../rust-radio-api" }
nom = "= 4.2.3"
serial = "= 0.4"
crc16 = "= 0.3.4"
chrono = "= 0.4.6"
failure = "= 0.1.5"
