[package]
name = "mai400-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
juniper =  "0.11"
kubos-service = { path = "../kubos-service" }
log = "^0.4.0"
mai400-api = { path = "../../apis/mai400-api" }
syslog = "4.0"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"
warp = "0.1.12"
