[package]
name = "telemetry-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
juniper =  "0.9.2"
"kubos-service" = { path = "../kubos-service" }