[package]
name = "telemetry-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
flate2 = "1.0"
juniper =  "0.9.2"
kubos-service = { path = "../kubos-service" }
kubos-telemetry-db = { path = "../../apis/telemetry-db-api" }
log = "^0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
syslog = "4.0"
tar = "0.4"

[dev-dependencies]
tempfile = "3"
time = "0.1"