[package]
name = "telemetry-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>", "Andrew Cantino <andrew@kubos.co>"]
edition = "2018"

[dependencies]
diesel = { version = "1.0.0", features = ["sqlite"] }
flate2 = "1.0"
juniper = { version = "0.14.2", default-features = false }
kubos-service = { path = "../kubos-service" }
kubos-telemetry-db = { path = "../../apis/telemetry-db-api" }
log = "^0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = { version = "1.0", default-features = false }
tar = { version = "0.4", default-features = false }
time = "0.1"

[dev-dependencies]
reqwest = "0.9.9"
tempfile = "3"
