[package]
name = "kubos-app-service"
version = "0.1.0"
authors = ["Marshall Culpepper <marshall@kubos.com>"]

[dependencies]
kubos-app = { path = "../../apis/app-api/rust" }
kubos-service = { path = "../kubos-service" }

failure = "0.1.2"
getopts = "0.2"
juniper =  "0.9.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4"
uuid = { version = "0.6", features = ["v4"] }

[dev-dependencies]
kubos-system = { path = "../../apis/system-api" }
serde_json = "1.0"
tempfile = "3"
