[package]
name = "isis-ants-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
failure = "0.1.2"
isis-ants-api = { path = "../../apis/isis-ants-api" }
juniper =  "0.9"
kubos-service = { path = "../kubos-service" }
log = "^0.4.0"
syslog = "4.0"

[dev-dependencies]
double = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"