[package]
name = "nsl-duplex-d2-comms-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.com>"]
edition = "2018"

[dependencies]
failure = "0.1.3"
juniper =  "0.11"
kubos-comms = { path = "../../libs/kubos-comms" }
kubos-service = { path = "../../services/kubos-service" }
log = "^0.4.0"
nsl-duplex-d2 = { path = "../../apis/nsl-duplex-d2" }
