[package]
name = "scheduler-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.7", default-features = false }
failure = { version = "0.1.2", default-features = false }
juniper = { version = "0.14.2", default-features = false }
kubos-service = { path = "../kubos-service" }
log = { version = "^0.4.0", default-features = false }
reqwest = { version = "0.10.1", default-features = false, features = ["blocking", "json"] }
serde_json = { version = "1.0", default-features = false }
serde = { version = "1.0", features = ["derive"]}
syslog = { version = "4.0", default-features = false }
tokio = { version = "0.1", default-features = false }
futures = { version = "*", default-features = false }

[dev-dependencies]
tempfile = "3.0"
utils = { path = "../../utils" }


