[package]
name = "scheduler-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
chrono = "= 0.4.6"
failure = "= 0.1.5"
juniper = "= 0.11"
kubos-service = { path = "../kubos-service" }
log = "^0.4.0"
reqwest = "=0.9.14"
serde_json = "= 1.0"
serde = { version = "= 1.0", features = ["derive"]}
syslog = "= 4.0"
tokio = "= 0.1"
futures = "*"

[dev-dependencies]
tempfile = "= 3.0"
utils = { path = "../../utils" }


