[package]
name = "scheduler-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
failure = "0.1.2"
juniper = "0.11"
kubos-service = { path = "../kubos-service" }
log = "^0.4.0"
reqwest = "0.9.9"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"]}
syslog = "4.0"
tokio = "1.8"
futures = "*"

[dev-dependencies]
tempfile = "3.0"
utils = { path = "../../utils" }


