[package]
name = "novatel-oem6-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
failure = "0.1.2"
juniper =  "0.9"
kubos-service = { path = "../kubos-service" }
log = "^0.4.0"
novatel-oem6-api = { path = "../../apis/novatel-oem6-api" }
syslog = "4.0"

[dev-dependencies]
serde_json = "1.0.10"