[package]
name = "novatel-oem6-service"
version = "0.1.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]

[dependencies]
failure = { git = "https://github.com/rust-lang-nursery/failure" }
juniper =  "0.9"
kubos-service = { path = "../kubos-service" }
novatel-oem6-api = { path = "../../apis/novatel-oem6-api" }

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"