[package]
name = "monitor-service"
version = "0.1.0"
authors = ["Marshall Culpepper <marshall@kubos.com>"]

[dependencies]
failure = "0.1.2"
juniper = "0.9"
kubos-service = { path = "../kubos-service" }
text_io = "0.1"

[dev-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0.10"
lazy_static = "1.1.0"
