[package]
name = "ethernet-service"
version = "0.1.0"
authors = ["William Greer <wgreer184@gmail.com>"]

[dependencies]
failure = "0.1.3"
comms-service = { path = "../../libs/comms-service" }
log = "^0.4.0"
syslog = "4.0"