[package]
name = "nosengine-rust"
version = "0.1.0"
authors = ["Timothy Scott <tmscott@mix.wvu.edu>"]
build = "build.rs"
edition = "2018"

[dependencies]
libc = "0.2.0"
failure = "0.1.2"

[build-dependencies]
cmake = "0.1"
