[package]
name = "clyde-3g-eps-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>", "Catherine Garabedian <catherine@kubos.co>"]
edition = "2018"

[dependencies]
clyde-3g-eps-api = { path = "../../apis/clyde-3g-eps-api" }
eps-api = { path = "../../apis/eps-api" }
failure = "0.1.2"
kubos-service = { path = "../kubos-service" }
juniper =  "0.11"
rust-i2c = { path = "../../hal/rust-hal/rust-i2c" }

[dev-dependencies]
serde_json = "1.0"
warp = "0.1.12"