[package]
name = "utils"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
tempfile = "3"
reqwest = { version = "0.9.9", default-features = false }
serde_json = "1.0"
warp = "0.1.12"
