[package]
name = "example-rust-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
kubos-service = { path = "../../services/kubos-service" }
juniper =  "0.15"
log = "^0.4.0"
mount = "0.3.0"

[package.metadata.release]
release = false
