[app-service.addr]
ip = "127.0.0.1"
port = 8000

[telemetry-service]
database = "telemetry.db"
direct_port = 8001

[telemetry-service.addr]
ip = "127.0.0.1"
port = 8002

[file-transfer-service]
storage_dir = "file-storage"

[file-transfer-service.addr]
ip = "127.0.0.1"
port = 8003

[monitor-service.addr]
ip = "127.0.0.1"
port = 8004

[shell-service.addr]
ip = "127.0.0.1"
port = 8005