[package]
name = "kubos-file-client"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]
edition = "2018"

[dependencies]
clap = "= 2.32"
simplelog = "^0.5.0"
log = "^0.4.0"
file-protocol = { path = "../../libs/file-protocol" }
failure = "= 0.1.5"
